Repository AY2324S1-CS2103T-T17-3/tp, pull requests merged in 2023-11, with the labels that each got.

#212 Split main window view into half for tutors and half for schedules
  src/main/java/seedu/address/ui/ListsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ListsPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ScheduleListCard.fxml
Labels: priority.High, type.Task

#214 Add list for calendar view into ModelManager
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ShowCalendarCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/schedule/ScheduleIsOnDatePredicate.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/ListsPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowCalendarCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/schedule/ScheduleIsOnDatePredicateTest.java
Labels: priority.High, type.Bug, severity.High

#217 Update main window title to TutorConnect
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Task

#199 Update landing page
  docs/images/Ui.png
  docs/index.md
Labels: priority.High, type.Documentation

#211 Add current datetime to status bar
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
Labels: priority.Low, type.Task

#220 Fix schedules position in calendar view
  src/main/java/seedu/address/ui/CalendarRow.java
Labels: priority.High, type.Bug, severity.High

#210 Update add-t, edit-s, theme in UG
  docs/UserGuide.md
  docs/images/addTutor.png
  docs/images/addTutorCommandSyntax.png
  docs/images/changeTheme.png
  docs/images/editSchedule.png
  docs/images/editScheduleCommandSyntax.png
  docs/images/themeCommandSyntax.png
Labels: priority.High, type.Documentation

#200 Modified list-s to add optional parameter <tutorindex>
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ListScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListScheduleCommandParser.java
  src/main/java/seedu/address/model/schedule/TutorNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/schedule/TutorPredicate.java
  src/test/java/seedu/address/logic/commands/ListScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListScheduleCommandParserTest.java
  src/test/java/seedu/address/model/schedule/TutorPredicateTest.java
Labels: priority.High, type.Task

#209 Modified list-s to include status m/0 and m/1
  src/main/java/seedu/address/logic/commands/ListScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ListScheduleCommandParser.java
  src/main/java/seedu/address/model/schedule/StatusPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/ListScheduleCommandParserTest.java
  src/test/java/seedu/address/model/schedule/StatusPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High, type.Task

#221 Update edit-t, find-t, unmark, show, clear, help in UG
  docs/UserGuide.md
  docs/images/clearAddressBook.png
  docs/images/editScheduleCommandSyntax.png
  docs/images/editTutor.png
  docs/images/editTutorCommandSyntax.png
  docs/images/findTutor.png
  docs/images/findTutorCommandSyntax.png
  docs/images/helpWindow.png
  docs/images/showCalendar.png
  docs/images/showCommandSyntax.png
  docs/images/uiOverview.png
  docs/images/unmarkSchedule.png
  docs/images/unmarkScheduleCommandSyntax.png
Labels: priority.High, type.Documentation

#177 Add separator for past schedules in Ui
  src/main/java/seedu/address/ui/ScheduleListPanel.java
Labels: priority.Low, type.Task

#224 Change schedules to only allow schedules that start and end on the same day
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/FindScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/ListScheduleCommandTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/model/schedule/UniqueScheduleListTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: priority.High, type.Task

#229 Fix predicate not clearing on show calendar
  src/main/java/seedu/address/logic/commands/ShowCalendarCommand.java
Labels: priority.High, type.Bug, severity.High

#226 Update ug for add-s
  docs/UserGuide.md
  docs/images/addSchedule.png
  docs/images/addScheduleCommandSyntax.png
Labels: priority.High, type.Documentation

#225 Update tutorial in UG
  docs/UserGuide.md
  docs/images/tutorial/add-s.png
  docs/images/tutorial/add-t.png
  docs/images/tutorial/mark.png
  docs/images/tutorial/schedule-index.png
  docs/images/tutorial/start.png
  docs/images/tutorial/tutor-index.png
Labels: priority.High, type.Documentation

#235 Add JAR release for v1.3
  src/main/java/seedu/address/MainApp.java
Labels: priority.High, type.Task

#236 Update ug list schedule wording
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#233 Update list-t, delete-t and mark schedule in UG
  docs/UserGuide.md
  docs/images/deleteTutor.png
  docs/images/deleteTutorCommandSyntax.png
  docs/images/listTutor.png
  docs/images/markSchedule.png
  docs/images/markScheduleCommandSyntax.png
  docs/images/themeCommandSyntax.png
Labels: priority.High, type.Documentation

#239 Add fullstops to UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#238 Update delete-s in UG
  docs/UserGuide.md
  docs/images/delete-schedules/delete-s-syntax.png
  docs/images/delete-schedules/delete-s.png
Labels: priority.High, type.Documentation

#242 Update UG search behaviour
  docs/UserGuide.md
  docs/images/deleteTutorCommandSyntax.png
  docs/images/findTutorCommandSyntax.png
  docs/images/markScheduleCommandSyntax.png
  docs/images/showCommandSyntax.png
  docs/images/themeCommandSyntax.png
  docs/images/unmarkScheduleCommandSyntax.png
Labels: priority.High, type.Documentation

#293 Fix bug for multiple prefixes in mark command
  src/main/java/seedu/address/logic/parser/MarkScheduleCommandParser.java
Labels: priority.High, type.Bug, bug.MustFix

#291 Fix parsing and display of year 0000
  src/main/java/seedu/address/model/schedule/Time.java
Labels: priority.High, type.Bug, bug.MustFix

#296 Add test for bug fix of multiple prefixes for mark command
  src/test/java/seedu/address/logic/parser/MarkScheduleCommandParserTest.java
Labels: priority.High, type.Bug, bug.MustFix

#244 Update DG with implementation details
  docs/DeveloperGuide.md
  docs/diagrams/AddTutorActivityDiagram.puml
  docs/diagrams/ChangeThemeSequenceDiagram.puml
  docs/diagrams/EditScheduleActivityDiagram.puml
  docs/diagrams/EditScheduleSequenceDiagram.puml
  docs/images/AddTutorActivityDiagram.png
  docs/images/ChangeThemeSequenceDiagram.png
  docs/images/EditScheduleActivityDiagram.png
  docs/images/EditScheduleSequenceDiagram.png
Labels: priority.High, type.Documentation

#297 Add exit command into UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#301 Fix status lost on tutor edit
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Bug, bug.MustFix

#302 Add documentation on filtered tutor list in calendar view
  docs/UserGuide.md
Labels: type.Bug, type.Documentation, bug.MustFix

#303 Truncate calendar view when schedules are short
  docs/UserGuide.md
  src/main/java/seedu/address/ui/CalendarCard.java
Labels: priority.High, type.Bug, bug.MustFix

#304 Update planned enhancements
  docs/DeveloperGuide.md
Labels: type.Bug, type.Documentation

#305 Prevent long fields from being truncated
  src/main/resources/view/CalendarRow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ScheduleListCard.fxml
Labels: priority.High, type.Bug, bug.MustFix

#298 Update find keyword behaviour and Back to Top for footnote
  docs/UserGuide.md
  docs/images/find-schedules/find-s-syntax.png
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Documentation, bug.MustFix

#306 Fixed list-s to update schedules before today after the day has passed
  src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
Labels: priority.High, type.Task, bug.MustFix

#307 Update planned enhancements in DG
  docs/DeveloperGuide.md
Labels: type.Bug, type.Documentation

#205 Update ruishanteo PPP
  docs/team/ruishanteo.md
Labels: priority.High, type.Documentation

#311 Prevent malformed json save file from crashing app on startup
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/test/java/seedu/address/storage/JsonAdaptedScheduleTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: priority.High, type.Bug, severity.High

#308 Update planned enhancements
  docs/DeveloperGuide.md
Labels: type.Bug, type.Documentation

#300 Add alternative way to open jar file in UG quick start
  docs/UserGuide.md
Labels: priority.High, type.Documentation, bug.MustFix

#299 Update UG for v1.4
  docs/UserGuide.md
  docs/images/find-schedules/find-s-syntax.png
Labels: priority.High, type.Documentation

#312 Add implementation details for find-t, unmark and show in DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/EditTutorActivityDiagram.puml
  docs/diagrams/EditTutorSequenceDiagram.puml
  docs/diagrams/FindTutorActivityDiagram.puml
  docs/diagrams/FindTutorSequenceDiagram.puml
  docs/diagrams/ShowCalendarActivityDiagram.puml
  docs/diagrams/ShowCalendarSequenceDiagram.puml
  docs/diagrams/UnmarkScheduleActivityDiagram.puml
  docs/diagrams/UnmarkScheduleSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/EditTutorActivityDiagram.png
  docs/images/EditTutorSequenceDiagram.png
  docs/images/FindTutorActivityDiagram.png
  docs/images/FindTutorSequenceDiagram.png
  docs/images/ShowCalendarActivityDiagram.png
  docs/images/ShowCalendarSequenceDiagram.png
  docs/images/UnmarkScheduleActivityDiagram.png
  docs/images/UnmarkScheduleSequenceDiagram.png
Labels: type.Documentation

#315 Update Planned enhancements - list schedule by pending
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#319 Update UG
  docs/UserGuide.md
  docs/images/findTutorCommandSyntax.png
  docs/images/list-schedules/list-s-completed.png
  docs/images/list-schedules/list-s-missed.png
  docs/images/list-schedules/list-s-tutor.png
  docs/images/list-schedules/list-s.png
Labels: priority.High, type.Documentation

#323 Revert time related error messages
  src/main/java/seedu/address/model/schedule/EndTime.java
  src/main/java/seedu/address/model/schedule/StartTime.java
  src/main/java/seedu/address/model/schedule/Time.java
Labels: type.Bug, bug.MustFix

#316 Update dishenggg PPP
  docs/team/dishenggg.md
Labels: priority.High, type.Documentation

#309 Update jweng88 PPP
  docs/team/jweng88.md
Labels: priority.High, type.Documentation

#245 Update mfjkri PPP
  docs/team/mfjkri.md
Labels: priority.High, type.Documentation

#327 Update known issues in UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#325 Improve StatusPredicate to compare status directly instead of its string comparison
  src/main/java/seedu/address/logic/commands/ListScheduleCommand.java
  src/main/java/seedu/address/model/schedule/StatusPredicate.java
  src/test/java/seedu/address/logic/commands/ListScheduleCommandTest.java
  src/test/java/seedu/address/model/schedule/StatusPredicateTest.java
Labels: priority.High, type.Task

#318 Add implementation details for list-s and find-s in DG
  docs/DeveloperGuide.md
  docs/diagrams/FindScheduleActivityDiagram.puml
  docs/diagrams/FindScheduleSequenceDiagram.puml
  docs/diagrams/ListScheduleActivityDiagram.puml
  docs/diagrams/ListScheduleSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/FindScheduleActivityDiagram.png
  docs/images/FindScheduleSequenceDiagram.png
  docs/images/ListScheduleActivityDiagram.png
  docs/images/ListScheduleSequenceDiagram.png
Labels: priority.High, type.Documentation

#313 Update saltedfishxx PPP
  docs/team/saltedfishxx.md
Labels: priority.High, type.Documentation

#320 Update DG for v1.4
  docs/DeveloperGuide.md
  docs/diagrams/DeleteTutorActivityDiagram.puml
  docs/diagrams/DeleteTutorSequenceDiagram.puml
  docs/diagrams/ListTutorActivityDiagram.puml
  docs/diagrams/ListTutorSequenceDiagram.puml
  docs/diagrams/MarkScheduleActivityDiagram.puml
  docs/diagrams/MarkScheduleSequenceDiagram.puml
  docs/images/DeleteTutorActivityDiagram.png
  docs/images/DeleteTutorSequenceDiagram.png
  docs/images/ListTutorActivityDiagram.png
  docs/images/ListTutorSequenceDiagram.png
  docs/images/MarkScheduleActivityDiagram.png
  docs/images/MarkScheduleSequenceDiagram.png
Labels: priority.High, type.Documentation

#331 Add hyperlinks to command summary
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#332 Add planned enhancement for help window flickering
  docs/DeveloperGuide.md
Labels: type.Bug, type.Documentation

#339 Update UG formatting
  docs/UserGuide.md
  docs/images/editTutor.png
Labels: type.Documentation

#333 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ChangeThemeSequenceDiagram.puml
  docs/images/ChangeThemeSequenceDiagram.png
Labels: priority.High, type.Documentation

#340 Remove blank page in UG
  docs/UserGuide.md
Labels: type.Documentation

#341 Add JAR release for v1.4
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#342 Remove reverted bug fixes from mfjkri PPP
  docs/team/mfjkri.md
Labels: type.Documentation

#343 Update value proposition
  docs/DeveloperGuide.md
Labels: type.Documentation

#344 Update jweng88 PPP
  docs/team/jweng88.md
Labels: priority.High, type.Documentation

#346 Update DG formatting + PPP
  docs/DeveloperGuide.md
  docs/team/dishenggg.md
Labels: priority.High, type.Documentation

#348 Update theme sequence diagram and add fullstops to use case
  docs/DeveloperGuide.md
  docs/diagrams/ChangeThemeSequenceDiagram.puml
  docs/images/ChangeThemeSequenceDiagram.png
Labels: type.Documentation

#349 Update linked PR in UG section of PPP
  docs/team/jweng88.md
Labels: priority.High, type.Documentation

#351 Update formatting in PPP
  docs/team/jweng88.md
Labels: priority.High, type.Documentation

#354 Update sequence diagrams
  docs/DeveloperGuide.md
  docs/diagrams/AddScheduleSequenceDiagram.puml
  docs/diagrams/AddTutorSequenceDiagram.puml
  docs/diagrams/ChangeThemeSequenceDiagram.puml
  docs/diagrams/EditScheduleSequenceDiagram.puml
  docs/diagrams/EditTutorSequenceDiagram.puml
  docs/diagrams/FindTutorSequenceDiagram.puml
  docs/diagrams/MarkScheduleSequenceDiagram.puml
  docs/diagrams/ShowCalendarSequenceDiagram.puml
  docs/diagrams/UnmarkScheduleSequenceDiagram.puml
  docs/images/AddScheduleSequenceDiagram.png
  docs/images/AddTutorSequenceDiagram.png
  docs/images/ChangeThemeSequenceDiagram.png
  docs/images/EditScheduleSequenceDiagram.png
  docs/images/EditTutorSequenceDiagram.png
  docs/images/FindTutorSequenceDiagram.png
  docs/images/MarkScheduleSequenceDiagram.png
  docs/images/ShowCalendarSequenceDiagram.png
  docs/images/UnmarkScheduleSequenceDiagram.png
Labels: type.Documentation

#358 Update sequence diagram for edit-s
  docs/DeveloperGuide.md
  docs/diagrams/EditScheduleSequenceDiagram.puml
  docs/images/EditScheduleSequenceDiagram.png
Labels: type.Documentation
