Repository AY2324S1-CS2103T-T17-3/tp, pull requests merged in 2023-10, with the labels that each got.

#29 Add AboutUs section for Muhammad Fikri
  docs/AboutUs.md
Labels: priority.High, type.Documentation

#32 Add AboutUs section for Rui Shan
  docs/AboutUs.md
  docs/images/ruishanteo.png
Labels: priority.High, type.Documentation

#31 Add AboutUs section for Di Sheng
  docs/AboutUs.md
  docs/images/dishenggg.png
Labels: priority.High, type.Documentation

#33 Add placeholder image for AboutUs section
  docs/AboutUs.md
  docs/images/mfjkri.png
Labels: priority.High, type.Documentation

#30 Add AboutUs section for Joshua Weng Hao
  docs/AboutUs.md
  docs/images/jweng88.png
Labels: priority.High, type.Documentation

#28 Update README for TutorConnect v1.1
  README.md
  docs/images/Ui.png
Labels: priority.High, type.Documentation

#34 Add User Guide for TutorConnect v1.1
  docs/UserGuide.md
  docs/images/addTutor.png
Labels: priority.High, type.Documentation

#37 Add add-s command to UG
  docs/UserGuide.md
  docs/images/addSchedule.png
Labels: priority.High, type.Documentation

#46 Add AboutUs section for Xuan Yi
  docs/AboutUs.md
  docs/images/saltedfishxx.png
Labels: priority.High, type.Documentation

#45 Create PPP skeleton for Xuan Yi
  docs/team/saltedfishxx.md
Labels: priority.High, type.Documentation

#35 Update Developer Guide for v1.1
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#47 Add list-t command to UG
  docs/UserGuide.md
  docs/images/listTutor.png
Labels: priority.High, type.Documentation

#48 Add delete-t command to UG
  docs/UserGuide.md
  docs/images/deleteTutor.png
Labels: priority.High, type.Documentation

#52 Add find command to UG
  docs/UserGuide.md
  docs/images/findTutor.png
Labels: priority.High, type.Documentation

#51 Standardise UG format
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#53 Standardise UG format
  docs/UserGuide.md
  docs/images/deleteTutor.png
  docs/images/listTutor.png
Labels: priority.High, type.Documentation

#49 Add delete-s command to UG
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/deleteSchedule.png
Labels: priority.High, type.Documentation

#50 Add list-s command to UG
  docs/UserGuide.md
  docs/images/emptyScheduleList.png
  docs/images/viewSchedule.png
Labels: priority.High, type.Documentation

#61 Add tutor function
  docs/UserGuide.md
  docs/images/addTutor.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTutorCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddTutorCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddTutorCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddTutorCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddTutorCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#60 Update find command to display as tutors
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.Story, priority.High

#70 Update header comments
  src/main/java/seedu/address/logic/commands/AddTutorCommand.java
  src/main/java/seedu/address/logic/parser/AddTutorCommandParser.java
  src/test/java/seedu/address/logic/commands/AddTutorCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddTutorCommandTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Story, priority.High

#74 Update edit person command
  src/main/java/seedu/address/logic/commands/EditTutorCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditTutorCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditTutorCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Task

#76 Fix tests for coverage
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditTutorCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: priority.High, type.Task

#81 Remove Address and Tag model class
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: priority.High, type.Task

#83 Fix ParserUtil coverage
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, type.Task

#84 Update edit tutor command word
  src/main/java/seedu/address/logic/commands/EditTutorCommand.java
Labels: priority.High, type.Task

#85 Add instantiation test for Messages
  src/test/java/seedu/address/logic/MessagesTest.java
Labels: priority.High, type.Task

#89 Refactor ListCommandTest to ListTutorCommandTest
  src/test/java/seedu/address/logic/commands/ListTutorCommandTest.java
Labels: priority.High, type.Task

#71 Add schedule object
  src/main/java/seedu/address/model/schedule/EndTime.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/StartTime.java
  src/main/java/seedu/address/model/schedule/Time.java
  src/test/java/seedu/address/model/schedule/EndTimeTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/model/schedule/StartTimeTest.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: priority.High, type.Task

#97 Add unique schedule list
  src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
  src/main/java/seedu/address/model/schedule/exceptions/DuplicateScheduleException.java
  src/main/java/seedu/address/model/schedule/exceptions/ScheduleNotFoundException.java
  src/test/java/seedu/address/model/schedule/UniqueScheduleListTest.java
Labels: priority.High, type.Task

#72 Add schedule parser
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/schedule/EndTime.java
  src/main/java/seedu/address/model/schedule/StartTime.java
  src/main/java/seedu/address/model/schedule/Time.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/ScheduleUtil.java
Labels: priority.High, type.Task

#99 Update Model and ModelManager to include schedules
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddTutorCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Task

#101 Update AddressBookTest file
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High, type.Task

#91 Add schedule command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/testutil/ScheduleUtil.java
Labels: priority.High, type.Task

#105 Update user guide for list-t and delete-t command
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#111 Update formatter to be static in JsonAdaptedSchedule
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: priority.High, type.Bug

#114 Remove Address from PersonCard UI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High, type.Bug

#106 Add list schedule command
  src/main/java/seedu/address/logic/commands/ListScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ListScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Task

#117 Delete tutor schedules
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Bug

#136 Edit schedule command
  docs/UserGuide.md
  docs/images/editSchedule.png
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditScheduleCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditScheduleDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditScheduleCommandParserTest.java
  src/test/java/seedu/address/testutil/EditScheduleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Story, priority.High

#139 Add implementation details for edit tutor in DG
  docs/DeveloperGuide.md
  docs/diagrams/EditTutorActivityDiagram.puml
  docs/diagrams/EditTutorSequenceDiagram.puml
  docs/images/EditTutorActivityDiagram.png
  docs/images/EditTutorSequenceDiagram.png
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditTutorCommandParser.java
  src/test/java/seedu/address/logic/parser/EditTutorCommandParserTest.java
Labels: priority.High, type.Documentation

#140 Add implementation details for add tutor in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddTutorActivityDiagram.puml
  docs/diagrams/AddTutorSequenceDiagram.puml
  docs/images/AddTutorActivityDiagram.png
  docs/images/AddTutorSequenceDiagram.png
Labels: priority.High, type.Documentation

#133 Add status to schedule
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/Status.java
  src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/main/java/seedu/address/ui/ScheduleCard.java
  src/main/resources/view/ScheduleListCard.fxml
  src/test/data/JsonAdaptedScheduleTest/typicalPersonsAndScheduleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/clashingScheduleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidScheduleAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedScheduleTest.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: priority.High, type.Task

#142 Add implementation details for delete tutor in DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteTutorActivityDiagram.puml
  docs/diagrams/DeleteTutorSequenceDiagram.puml
  docs/images/DeleteTutorActivityDiagram.png
  docs/images/DeleteTutorSequenceDiagram.png
Labels: priority.High, type.Documentation

#141 Add AddScheduleCommand implementation details to DG
  docs/DeveloperGuide.md
  docs/diagrams/AddScheduleActivityDiagram.puml
  docs/diagrams/AddScheduleSequenceDiagram.puml
  docs/images/AddScheduleActivityDiagram.png
  docs/images/AddScheduleSequenceDiagram.png
Labels: priority.High, type.Documentation

#144 Add mark command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/MarkScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/schedule/Status.java
  src/test/java/seedu/address/logic/commands/MarkScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, type.Task

#149 Add headers, edit-s summary, and glossary
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#154 Add UI overview and FAQs to UG
  docs/UserGuide.md
  docs/images/uiOverview.png
Labels: priority.High, type.Documentation

#153 Add unmark command to UG
  docs/UserGuide.md
  docs/images/unmarkSchedule.png
Labels: priority.High, type.Documentation

#143 Add sorting to UniqueScheduleList
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/Time.java
  src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
  src/test/java/seedu/address/model/schedule/EndTimeTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/model/schedule/StartTimeTest.java
  src/test/java/seedu/address/model/schedule/TimeTest.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
Labels: type.Story, priority.High

#158 Enable assertions for project
  build.gradle
Labels: priority.High, type.Task

#156 Add edit tutor command to UG
  docs/UserGuide.md
  docs/images/editTutor.png
Labels: priority.High, type.Documentation

#162 Update DG to include delete-s implementation
  docs/DeveloperGuide.md
  docs/diagrams/DeleteScheduleActivityDiagram.puml
  docs/diagrams/DeleteScheduleSequenceDiagram.puml
  docs/images/DeleteScheduleActivityDiagram.png
  docs/images/DeleteScheduleSequenceDiagram.png
Labels: priority.High, type.Documentation

#163 Update AddressBookParser test
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditScheduleDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/EditScheduleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ScheduleUtil.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: type.Story, priority.High

#167 Update error message for invalid schedule status
  src/main/java/seedu/address/model/schedule/Status.java
Labels: priority.High, type.Task

#171 Fix EditScheduleCommand
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/testutil/EditScheduleDescriptorBuilder.java
Labels: priority.High, type.Bug

#175 Add parser unmark command test
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Task

#145 Update SampleDataUtil to include schedules
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: priority.Low, type.Task

#178 Add more tests for UniqueScheduleList
  src/test/java/seedu/address/model/schedule/UniqueScheduleListTest.java
Labels: priority.High, type.Task

#181 Update URL in HelpWindow
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, type.Task

#150 Preserve schedule status after edit
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
Labels: priority.High, type.Task

#180 Remove seconds from time related commands
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
  src/main/java/seedu/address/model/schedule/Time.java
  src/test/data/JsonSerializableAddressBookTest/clashingScheduleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidScheduleAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/schedule/EndTimeTest.java
  src/test/java/seedu/address/model/schedule/StartTimeTest.java
  src/test/java/seedu/address/model/schedule/TimeTest.java
Labels: priority.High, type.Task

#182 Add parser mark command test
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, type.Task

#166 Add mark command to the UG
  docs/UserGuide.md
  docs/images/markSchedule.png
Labels: priority.High, type.Documentation

#174 Add draft tutorial for UG
  docs/UserGuide.md
  docs/images/tutorial/add-s.png
  docs/images/tutorial/add-t.png
  docs/images/tutorial/list-s.png
  docs/images/tutorial/start.png
  docs/images/tutorial/tutor-index.png
Labels: priority.High, type.Documentation

#186 Update associated schedule's tutors when tutor is edited
  src/main/java/seedu/address/logic/commands/EditTutorCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTutorCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Bug, severity.High

#184 Add tests for CliSyntax
  src/test/java/seedu/address/logic/parser/CliSyntaxTest.java
Labels: priority.High, type.Task

#176 Update ug v1.3 for list-s and other QoL navagability
  docs/UserGuide.md
  docs/images/listScheduleAll.png
  docs/images/listScheduleFilter.png
Labels: priority.High, type.Documentation

#188 Update parser method and usage message of mark command
  src/main/java/seedu/address/logic/commands/MarkScheduleCommand.java
  src/main/java/seedu/address/logic/parser/MarkScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/schedule/Status.java
  src/test/java/seedu/address/logic/commands/MarkScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MarkScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/schedule/StatusTest.java
Labels: priority.High, type.Task

#151 Update UG for v1.3
  docs/UserGuide.md
  docs/images/editTutor.png
  docs/images/listScheduleAll.png
  docs/images/listScheduleFilter.png
  docs/images/markSchedule.png
  docs/images/tutorial/add-s.png
  docs/images/tutorial/add-t.png
  docs/images/tutorial/list-s.png
  docs/images/tutorial/start.png
  docs/images/tutorial/tutor-index.png
  docs/images/uiOverview.png
  docs/images/unmarkSchedule.png
Labels: priority.High, type.Documentation

#137 Implement mark schedule
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
  src/main/java/seedu/address/logic/commands/MarkScheduleCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnmarkScheduleCommandParser.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/Status.java
  src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/main/java/seedu/address/ui/ScheduleCard.java
  src/main/resources/view/ScheduleListCard.fxml
  src/test/data/JsonAdaptedScheduleTest/typicalPersonsAndScheduleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/clashingScheduleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidScheduleAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MarkScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CliSyntaxTest.java
  src/test/java/seedu/address/logic/parser/MarkScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UnmarkScheduleCommandParserTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/model/schedule/StatusTest.java
  src/test/java/seedu/address/storage/JsonAdaptedScheduleTest.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: priority.High, type.Epic

#165 Add find-s command to find schedules by tutor name
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ListScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindScheduleCommandParser.java
  src/main/java/seedu/address/model/schedule/TutorNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindScheduleCommandParserTest.java
  src/test/java/seedu/address/model/schedule/TutorNameContainsKeywordsPredicateTest.java
Labels: priority.High, type.Task

#202 Rename find to find-t
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindTutorCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTutorCommandParser.java
  src/test/java/seedu/address/logic/commands/FindTutorCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindTutorCommandParserTest.java
Labels: priority.High, type.Task

#204 Replace occurrences of Tutor Connect with TutorConnect
  README.md
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: priority.High, type.Documentation

#207 Update DG Design details
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: priority.High, type.Documentation

#196 Add calendar view
  docs/UserGuide.md
  docs/images/showCalendar.png
  src/main/java/seedu/address/logic/commands/ShowCalendarCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ShowCalendarCommandParser.java
  src/main/java/seedu/address/model/schedule/Date.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/Time.java
  src/main/java/seedu/address/ui/CalendarCard.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/CalendarRow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/CalendarCard.fxml
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/CalendarRow.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/test/java/seedu/address/logic/commands/ShowCalendarCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ShowCalendarCommandParserTest.java
  src/test/java/seedu/address/model/schedule/DateTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/model/schedule/TimeTest.java
Labels: type.Story, priority.High
